title: Stikbuf's Blog
theme: minima
header_pages:
  - R3S.md
  - rational-inference-of-brain-in-a-vat.md
exclude:
  - AGENTS.md
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - README.md
  - .local
  - tools
